// Brands with a logo file in public/brands/<slug>.svg: single-colour logos from Simple Icons
// 16.34.0 (CC0 icon data, see public/brands/README.md). Keys are brand names as stored in our
// database. Regenerate the files rather than editing them by hand.
export const BRAND_LOGOS: Record<string, string> = {
  Toyota: 'toyota',
  Volkswagen: 'volkswagen',
  Skoda: 'skoda',
  Renault: 'renault',
  Hyundai: 'hyundai',
  Kia: 'kia',
  BMW: 'bmw',
  Audi: 'audi',
  Nissan: 'nissan',
  Ford: 'ford',
  Mazda: 'mazda',
  Honda: 'honda',
  Mitsubishi: 'mitsubishi',
  Chevrolet: 'chevrolet',
  Tesla: 'tesla',
  Opel: 'opel',
  Peugeot: 'peugeot',
  Citroen: 'citroen',
  Fiat: 'fiat',
  Volvo: 'volvo',
  Subaru: 'subaru',
  Suzuki: 'suzuki',
  Infiniti: 'infiniti',
  Jeep: 'jeep',
  Porsche: 'porsche',
  MINI: 'mini',
  Dacia: 'dacia',
  SEAT: 'seat',
  Chrysler: 'chrysler',
  MG: 'mg',
  Smart: 'smart',
  Cadillac: 'cadillac',
  Acura: 'acura',
  Ram: 'ram',
  'ВАЗ / Lada': 'lada',
};
