// Brands whose model lists we fetch from auto.ria (one request each, cached 30 days).
// Together they cover most of the Ukrainian market; other brands keep a free-text model field.
export const MODEL_BRANDS = [
  'Toyota',
  'Volkswagen',
  'Skoda',
  'Renault',
  'Hyundai',
  'Kia',
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Nissan',
  'Ford',
  'Mazda',
  'Honda',
  'Mitsubishi',
  'Chevrolet',
  'Tesla',
  'Opel',
  'Peugeot',
  'Citroen',
  'Fiat',
  'Volvo',
  'Subaru',
  'Suzuki',
  'Lexus',
  'Infiniti',
  'Land Rover',
  'Jeep',
  'Dodge',
  'Porsche',
  'MINI',
  'Dacia',
  'SEAT',
  'Cupra',
  'Jaguar',
  'Chrysler',
  'BYD',
  'Geely',
  'Chery',
  'Zeekr',
  'Haval',
  'MG',
  'Daewoo',
  'SsangYong',
  'Smart',
  'Cadillac',
  'Lincoln',
  'Acura',
  'Genesis',
  'Ram',
  'GMC',
  'ВАЗ / Lada',
  'ЗАЗ',
];
